import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

export default function FeaturedAiReview() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate AI processing time
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1200);
    return () => clearTimeout(timer);
  }, []);

  const professorData = {
    fullName: "Prof. Dr. Mohammad Ubaidullah Bokhari",
    url: "https://mu-bokhari.vercel.app/"
  };

  if (loading) {
    return (
      <div className="container py-5 mt-5 text-center fade-in">
        <div className="mx-auto" style={{ maxWidth: '500px' }}>
          <div className="ai-scanner-container mb-4 shadow-lg" style={{ height: '300px', backgroundColor: '#0f172a', borderRadius: '20px', position: 'relative', overflow: 'hidden' }}>
            <div className="ai-scanner-line"></div>
            <div className="d-flex h-100 justify-content-center align-items-center flex-column text-white p-4">
              <i className="fas fa-robot fa-4x mb-3 pulse-primary text-white"></i>
              <h3 className="fw-bold text-white">AI Portfolio Review in Progress...</h3>
              <p className="opacity-75">Analyzing scholarly metadata and architectural integrity.</p>
              <div className="mt-3 w-75 bg-dark rounded overflow-hidden" style={{ height: '4px' }}>
                <div className="h-100 bg-primary pulse-primary" style={{ width: '100%', opacity: 0.5 }}></div>
              </div>
            </div>
          </div>
          <p className="text-dark fw-medium mt-3">
            <i className="fas fa-magic me-2 text-primary"></i>
            Our neural models are performing a deep-scan of the Professor's deployment.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="container py-5 mt-4 fade-in">
      {/* Header section */}
      <div className="d-flex justify-content-between align-items-start mb-4">
        <div>
          <h1 className="fw-bold text-primary mb-1">
            <i className="fas fa-shield-alt me-2"></i>Featured AI Portfolio Audit
          </h1>
          <p className="text-muted mb-0">
            Intelligent analysis for <strong className="text-dark">{professorData.fullName}'s Portfolio</strong>
          </p>
        </div>
        <Link to="/portfolios/featured/bokhari" className="btn btn-outline-secondary rounded-pill px-3">
          <i className="fas fa-arrow-left me-1"></i> Back to Showcase
        </Link>
      </div>

      {/* Stats Cards Section */}
      <div className="row g-4 mb-5">
        <div className="col-md-4">
          <div className="card h-100 border-0 shadow-sm p-4 text-center">
            <div className="rounded-circle bg-primary-subtle d-inline-flex p-3 mx-auto mb-3">
              <i className="fas fa-pager fs-3 text-primary"></i>
            </div>
            <h6 className="text-muted text-uppercase small fw-bold mb-2">Page Identity</h6>
            <h5 className="mb-0 text-dark fw-bold">Prof. Dr. M. U. Bokhari</h5>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card h-100 border-0 shadow-sm p-4 text-center">
            <div className="rounded-circle bg-info-subtle d-inline-flex p-3 mx-auto mb-3">
              <i className="fas fa-link fs-3 text-info"></i>
            </div>
            <h6 className="text-muted text-uppercase small fw-bold mb-2">Internal Links</h6>
            <h3 className="mb-0 text-dark fw-bold">42</h3>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card h-100 border-0 shadow-sm p-4 text-center">
            <div className="rounded-circle bg-success-subtle d-inline-flex p-3 mx-auto mb-3">
              <i className="fas fa-images fs-3 text-success"></i>
            </div>
            <h6 className="text-muted text-uppercase small fw-bold mb-2">Visual Assets</h6>
            <h3 className="mb-0 text-dark fw-bold">18</h3>
          </div>
        </div>
      </div>

      {/* Deep Dive Review Content */}
      <div className="row">
        <div className="col-lg-10 mx-auto">
          <div className="card border-0 shadow-lg mb-4" style={{ borderRadius: '24px', overflow: 'hidden' }}>
            <div className="card-header bg-white p-4 border-bottom d-flex align-items-center">
              <div className="bg-primary rounded-circle p-2 me-3 pulse-primary">
                <i className="fas fa-brain text-white"></i>
              </div>
              <div>
                <h2 className="mb-0 fs-4 fw-bold">Deep-Scan Technical Report</h2>
                <p className="text-muted small mb-0">Generated by PortfoliQue Neural Engine v2.4</p>
              </div>
            </div>
            
            <div className="card-body p-4 p-md-5">
              <div className="ai-report-detailed">
                <section className="mb-5">
                  <h4 className="fw-bold text-primary mb-3">1. Executive Overview</h4>
                  <p className="text-dark fs-5 mb-3" style={{ lineHeight: '1.7' }}>
                    The portfolio deployment at <code>mu-bokhari.vercel.app</code> serves as a superlative example of 
                    <strong> Academic Identity Architecture</strong>. Our analysis indicates a deliberate focus on 
                    hierarchical information delivery, ensuring that complex scholarly achievements are accessible 
                    to both institutional reviewers and the general public.
                  </p>
                  <div className="p-3 bg-light rounded-3 border-start border-primary border-5">
                    <span className="fw-bold">AI Verdict:</span> Exceptional professional authority with optimized semantic structure.
                  </div>
                </section>

                <section className="mb-5">
                  <h4 className="fw-bold text-primary mb-3">2. Design & UX Audit</h4>
                  <div className="row g-4">
                    <div className="col-md-6">
                      <div className="p-3 border rounded-3 h-100">
                        <h6 className="fw-bold"><i className="fas fa-palette me-2 text-warning"></i>Visual Consistency</h6>
                        <p className="small text-muted mb-0">
                          The use of a conservative, high-contrast color palette reinforces the Professor's established 
                          stature. Typography choices provide excellent legibility for dense research titles.
                        </p>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="p-3 border rounded-3 h-100">
                        <h6 className="fw-bold"><i className="fas fa-mouse-pointer me-2 text-info"></i>Interaction Design</h6>
                        <p className="small text-muted mb-0">
                          The navigation flow is streamlined. The 'Featured' section acts as a high-conversion landing zone, 
                          instantly presenting core accomplishments before requiring deeper scrolling.
                        </p>
                      </div>
                    </div>
                  </div>
                </section>

                <section className="mb-5">
                  <h4 className="fw-bold text-primary mb-3">3. Technical Integrity</h4>
                  <table className="table table-borderless bg-light rounded-3 p-3 mt-3">
                    <tbody>
                      <tr>
                        <td className="fw-bold py-3"><i className="fas fa-bolt me-2 text-success"></i>Performance</td>
                        <td className="py-3"><span className="badge bg-success">98/100</span> (LCP: 0.8s)</td>
                      </tr>
                      <tr>
                        <td className="fw-bold py-3"><i className="fas fa-universal-access me-2 text-primary"></i>Accessibility</td>
                        <td className="py-3"><span className="badge bg-primary">100/100</span> (WCAG 2.1 Compliant)</td>
                      </tr>
                      <tr>
                        <td className="fw-bold py-3"><i className="fas fa-search me-2 text-info"></i>SEO</td>
                        <td className="py-3"><span className="badge bg-info">95/100</span> (Optimized Meta Schema)</td>
                      </tr>
                    </tbody>
                  </table>
                </section>

                <section className="mb-4">
                  <h4 className="fw-bold text-primary mb-3">4. Strategic Recommendations</h4>
                  <div className="alert alert-info border-0 shadow-sm">
                    <ul className="mb-0">
                      <li className="mb-2"><strong>Search Capability:</strong> Implementing a fuzzy-search filter for the 'Publications' section would further enhance UX for research peers.</li>
                      <li><strong>Dynamic CV:</strong> A direct 'Download PDF' button synced with the site content would increase utility for institutional recruiters.</li>
                    </ul>
                  </div>
                </section>

                <div className="mt-5 text-center py-4 bg-primary text-white rounded-4 shadow-sm">
                  <h5 className="fw-bold mb-2">Final Neural Rating</h5>
                  <div className="display-4 fw-bold mb-0">S+</div>
                  <p className="small mb-0 text-white fw-medium">Tier: Professional Masterpiece</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {/* Action Footer */}
      <div className="text-center mt-4">
        <a href={professorData.url} target="_blank" rel="noopener noreferrer" className="btn btn-primary rounded-pill px-5 py-3 shadow-lg fw-bold">
          <i className="fas fa-external-link-alt me-2"></i> Visit Live Deployment
        </a>
      </div>
    </div>
  );
}
